Change working directory to package's root
Otherwise SocketStream throws:

    Error: You must change into the project directory before starting your SocketStream app
        at Object.<anonymous> (/usr/local/lib/node_modules/lamassu-admin/node_modules/socketstream/lib/socketstream.js:15:24)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Module.require (module.js:364:17)
        at require (module.js:380:17)
        at Object.<anonymous> (/usr/local/lib/node_modules/lamassu-admin/node_modules/socketstream/index.js:4:18)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)

@floating is there any way around this?